LgsKocu.Web/Areas/Admin/Controllers/AdminFileUploadController.cs
using System;
using System.IO;
using System.Web;
using System.Web.Mvc;

namespace LgsKocu.Web.Areas.Admin.Controllers
{
    public class AdminFileUploadController : Controller
    {
        [AcceptVerbs(HttpVerbs.Post)]
        public JsonResult UploadFile(HttpPostedFileBase aUploadedFile)
        {
            var vReturnImagePath = string.Empty;
            if (aUploadedFile.ContentLength > 0)
            {
                var vFileName = Path.GetFileNameWithoutExtension(aUploadedFile.FileName);
                var vExtension = Path.GetExtension(aUploadedFile.FileName);

                var sImageName = vFileName + DateTime.Now.ToString("YYYYMMDDHHMMSS");

                var vImageSavePath = Server.MapPath("/Assets/Files/Sayfa/") + sImageName + vExtension;
                //sImageName = sImageName + vExtension;  
                vReturnImagePath = "/Assets/Files/Sayfa/" + sImageName + vExtension;
                ViewBag.Msg = vImageSavePath;
                var path = vImageSavePath;

                // Saving Image in Original Mode  
                aUploadedFile.SaveAs(path);
                var vImageLength = new FileInfo(path).Length;
                //here to add Image Path to You Database ,  
                TempData["message"] = "Image was Added Successfully";
            }

            return Json(Convert.ToString(vReturnImagePath), JsonRequestBehavior.AllowGet);
        }
    }
}

LgsKocu.Web/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>LGSHAZIRLIK.NET CMS</title>
    <link href="~/Assets/Panel/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="~/Assets/Panel/summernote/summernote.min.css" rel="stylesheet" />
    <link href="~/Assets/Panel/js/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Assets/Panel/css/sb-admin-2.min.css" rel="stylesheet">
</head>
<body id="page-top">
    <div id="wrapper">
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/Admin/AdminCekilis">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">LGSHAZIRLIK <sup>.NET</sup></div>
            </a>
            <hr class="sidebar-divider my-0">

            <li class="nav-item">
                <a class="nav-link" href="/Admin/AdminCekilis">
                    <i class="fas fa-gifts"></i>
                    <span>Çekilişler</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/Admin/AdminDosya">
                    <i class="fas fa-file"></i>
                    <span>Dosyalar</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/Admin/AdminSoru">
                    <i class="far fa-question-circle"></i>
                    <span>Sorular</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/Admin/AdminSinif">
                    <i class="fas fa-graduation-cap"></i>
                    <span>Sınıflar</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/Admin/AdminDers">
                    <i class="fas fa-book"></i>
                    <span>Dersler</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/Admin/AdminKonu">
                    <i class="fas fa-book-open"></i>
                    <span>Konular</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/Admin/AdminUye">
                    <i class="fas fa-address-card"></i>
                    <span>Üyeler</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/Admin/AdminSayfa">
                    <i class="fas fa-scroll"></i>
                    <span>Sayfalar</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/Admin/AdminYazi">
                    <i class="fas fa-file-word"></i>
                    <span>Yazılar</span>
                </a>
            </li>
            <hr class="sidebar-divider">
            <li class="nav-item">
                <a class="nav-link" href="/Admin/Login">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Çıkış Yap</span>
                </a>
            </li>
            <hr class="sidebar-divider d-none d-md-block">
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>
        </ul>
        <div id="content-wrapper" class="d-flex flex-column">
            <div id="content">
                <div class="container-fluid" style="padding-top: 15px;">
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
    <script src="~/Assets/Panel/vendor/jquery/jquery.min.js"></script>
    <script src="~/Assets/Panel/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/Assets/Panel/vendor/jquery-easing/jquery.easing.min.js"></script>
    <script src="~/Assets/Panel/summernote/summernote.min.js"></script>
    <script src="~/Assets/Panel/js/sb-admin-2.min.js"></script>
    <script src="~/Assets/Panel/js/jquery-ui.min.js"></script>
    <script>
        $(document).ready(function () {

            $('.summernote').summernote({
                height: 300,
                minHeight: null,
                maxHeight: null,
                focus: false,
                callbacks: {
                    onImageUpload: function (files) {
                        for (let i = 0; i < files.length; i++) {
                            UploadImage(files[i]);
                        }
                    }
                }
            });

            function UploadImage(file) {
                var url = '@Url.Action("UploadFile", "AdminFileUpload")';
                formData = new FormData();
                formData.append("aUploadedFile", file);
                $.ajax({
                    type: 'POST',
                    url: url,
                    data: formData,
                    cache: false,
                    contentType: false,
                    processData: false,
                    success: function (FileUrl) {
                        var imgNode = document.createElement('img');
                        imgNode.src = FileUrl;
                        $('.summernote').summernote('insertNode', imgNode);
                    },
                    error: function (data) {
                        alert(data.responseText);
                    }
                });
            }

            $( ".datetimepicker" ).datepicker({
                dateFormat: "mm-dd-yy",
                altFormat: "mm-dd-yy",
                altField:"#tarih-db",
                monthNames: [ "Ocak", "Şubat", "Mart", "Nisan", "Mayıs", "Haziran", "Temmuz", "Ağustos", "Eylül", "Ekim", "Kasım", "Aralık" ],
                dayNamesMin: [ "Pa", "Pt", "Sl", "Ça", "Pe", "Cu", "Ct" ],
                firstDay:1
            });
        });

    </script>
</body>
</html>