LgsKocu.Web/Areas/Admin/Controllers/AdminCevapController.cs
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LgsKocu.Web.Database;

namespace LgsKocu.Web.Areas.Admin.Controllers
{
    public class AdminCevapController : Controller
    {
        private readonly LgsHazirlikEntities db = new LgsHazirlikEntities();

        public ActionResult Index()
        {
            var cevap = db.Cevap.Include(c => c.Soru).Include(c => c.Uye);
            return View(cevap.ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var cevap = db.Cevap.Find(id);
            if (cevap == null) return HttpNotFound();
            return View(cevap);
        }

        public ActionResult Create()
        {
            ViewBag.SoruId = new SelectList(db.Soru, "Id", "Baslik");
            ViewBag.UyeId = new SelectList(db.Uye, "Id", "Ad");
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Cevap cevap, HttpPostedFileBase imageFile)
        {
            if (ModelState.IsValid)
            {
                if (imageFile != null)
                {
                    if (imageFile.ContentLength > 0)
                    {
                        var path = Path.Combine(Server.MapPath("~/Assets/Files/Cevap/"), imageFile.FileName);
                        imageFile.SaveAs(path);

                        cevap.Gorsel = "/Assets/Files/Cevap/" + imageFile.FileName;
                    }
                }

                db.Cevap.Add(cevap);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.SoruId = new SelectList(db.Soru, "Id", "Baslik", cevap.SoruId);
            ViewBag.UyeId = new SelectList(db.Uye, "Id", "Ad", cevap.UyeId);
            return View(cevap);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var cevap = db.Cevap.Find(id);
            if (cevap == null) return HttpNotFound();
            ViewBag.SoruId = new SelectList(db.Soru, "Id", "Baslik", cevap.SoruId);
            ViewBag.UyeId = new SelectList(db.Uye, "Id", "Ad", cevap.UyeId);
            return View(cevap);
        }

        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Cevap cevap, HttpPostedFileBase imageFile)
        {
            if (ModelState.IsValid)
            {
                if (imageFile != null)
                {
                    if (imageFile.ContentLength > 0)
                    {
                        var path = Path.Combine(Server.MapPath("~/Assets/Files/Cevap/"), imageFile.FileName);
                        imageFile.SaveAs(path);

                        cevap.Gorsel = "/Assets/Files/Cevap/" + imageFile.FileName;
                    }
                }
                else
                {
                    cevap.Gorsel = db.Cevap.Find(cevap.Id).Gorsel;
                }

                db.Entry(cevap).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.SoruId = new SelectList(db.Soru, "Id", "Baslik", cevap.SoruId);
            ViewBag.UyeId = new SelectList(db.Uye, "Id", "Ad", cevap.UyeId);
            return View(cevap);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var cevap = db.Cevap.Find(id);
            if (cevap == null) return HttpNotFound();
            return View(cevap);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var cevap = db.Cevap.Find(id);
            db.Cevap.Remove(cevap);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing) db.Dispose();
            base.Dispose(disposing);
        }
    }
}

LgsKocu.Web/Areas/Admin/Controllers/AdminSoruController.cs
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LgsKocu.Web.Database;

namespace LgsKocu.Web.Areas.Admin.Controllers
{
    public class AdminSoruController : Controller
    {
        private readonly LgsHazirlikEntities db = new LgsHazirlikEntities();

        // GET: Admin/AdminSoru
        public ActionResult Index()
        {
            var soru = db.Soru.Include(s => s.Ders).Include(s => s.Sinif);
            return View(soru.ToList());
        }

        // GET: Admin/AdminSoru/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var soru = db.Soru.Find(id);
            if (soru == null) return HttpNotFound();
            return View(soru);
        }

        // GET: Admin/AdminSoru/Create
        public ActionResult Create()
        {
            ViewBag.UyeId = new SelectList(db.Uye, "Id", "Email");
            ViewBag.DersId = new SelectList(db.Ders, "Id", "Ad");
            ViewBag.SinifId = new SelectList(db.Sinif, "Id", "Ad");
            return View();
        }

        // POST: Admin/AdminSoru/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Soru soru, HttpPostedFileBase imageFile)
        {
            if (ModelState.IsValid)
            {
                if (imageFile != null)
                {
                    if (imageFile.ContentLength > 0)
                    {
                        var path = Path.Combine(Server.MapPath("~/Assets/Files/Soru/"), imageFile.FileName);
                        imageFile.SaveAs(path);

                        soru.Gorsel = "/Assets/Files/Soru/" + imageFile.FileName;
                    }
                }

                db.Soru.Add(soru);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UyeId = new SelectList(db.Uye, "Id", "Email");
            ViewBag.DersId = new SelectList(db.Ders, "Id", "Ad", soru.DersId);
            ViewBag.SinifId = new SelectList(db.Sinif, "Id", "Ad", soru.SinifId);
            return View(soru);
        }

        // GET: Admin/AdminSoru/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var soru = db.Soru.Find(id);
            if (soru == null) return HttpNotFound();
            ViewBag.UyeId = new SelectList(db.Uye, "Id", "Email");
            ViewBag.DersId = new SelectList(db.Ders, "Id", "Ad", soru.DersId);
            ViewBag.SinifId = new SelectList(db.Sinif, "Id", "Ad", soru.SinifId);
            return View(soru);
        }

        // POST: Admin/AdminSoru/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Soru soru, HttpPostedFileBase imageFile)
        {
            if (ModelState.IsValid)
            {
                if (imageFile != null)
                {
                    if (imageFile.ContentLength > 0)
                    {
                        var path = Path.Combine(Server.MapPath("~/Assets/Files/Soru/"), imageFile.FileName);
                        imageFile.SaveAs(path);

                        soru.Gorsel = "/Assets/Files/Soru/" + imageFile.FileName;
                    }
                }
                else
                {
                    soru.Gorsel = db.Soru.Find(soru.Id).Gorsel;
                }

                db.Entry(soru).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UyeId = new SelectList(db.Uye, "Id", "Email");
            ViewBag.DersId = new SelectList(db.Ders, "Id", "Ad", soru.DersId);
            ViewBag.SinifId = new SelectList(db.Sinif, "Id", "Ad", soru.SinifId);
            return View(soru);
        }

        // GET: Admin/AdminSoru/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var soru = db.Soru.Find(id);
            if (soru == null) return HttpNotFound();
            return View(soru);
        }

        // POST: Admin/AdminSoru/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var soru = db.Soru.Find(id);
            db.Soru.Remove(soru);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing) db.Dispose();
            base.Dispose(disposing);
        }
    }
}

LgsKocu.Web/Areas/Admin/Views/AdminSoru/Create.cshtml
@model LgsKocu.Web.Database.Soru

@{

    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("Create", "AdminSoru", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Soru Ekle</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UyeId, "UyeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UyeId", null, "-- Seçiniz --", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UyeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Baslik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Baslik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Baslik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Icerik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Icerik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Icerik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gorsel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="imageFile" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SinifId, "SinifId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SinifId", null, "-- Seçiniz --", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SinifId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DersId, "DersId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DersId", null, "-- Seçiniz --", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DersId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Durum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Durum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Durum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Ekle" class="btn btn-primary" />
                @Html.ActionLink("Geri Dön", "Index", null, new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
}

LgsKocu.Web/Areas/Admin/Views/AdminSoru/Delete.cshtml
@model LgsKocu.Web.Database.Soru

@{
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div>
    <h4>@Model.Baslik >> Sil</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UyeId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UyeId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Baslik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Baslik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Icerik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Icerik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gorsel)
        </dt>

        <dd>
            <img src="@Model.Gorsel" class="img-fluid" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Durum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Durum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ders.Ad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ders.Ad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sinif.Ad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sinif.Ad)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Sil" class="btn btn-primary"/>
            @Html.ActionLink("Geri Dön", "Index", null, new {@class = "btn btn-danger"})
        </div>
    }
</div>

LgsKocu.Web/Areas/Admin/Views/AdminSoru/Details.cshtml
@model LgsKocu.Web.Database.Soru

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div>
    <h4>@Model.Baslik >> Detay</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UyeId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UyeId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Baslik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Baslik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Icerik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Icerik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gorsel)
        </dt>

        <dd>
            <img src="@Model.Gorsel" class="img-fluid" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Durum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Durum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ders.Ad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ders.Ad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sinif.Ad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sinif.Ad)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Güncelle", "Edit", new { id = Model.Id }, new { @class = "btn btn-primary" }) |
    @Html.ActionLink("Sil", "Delete", new { id = Model.Id }, new { @class = "btn btn-warning" }) |
    @Html.ActionLink("Geri Dön", "Index", null, new { @class = "btn btn-danger" })
</p>

LgsKocu.Web/Areas/Admin/Views/AdminSoru/Edit.cshtml
@model LgsKocu.Web.Database.Soru

@{
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("Edit", "AdminSoru", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>@Model.Baslik >> Güncelle</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.UyeId, "UyeId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("UyeId", null, "-- Seçiniz --", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.UyeId, "", new { @class = "text-danger" })
        </div>
    </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Baslik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Baslik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Baslik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Icerik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Icerik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Icerik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gorsel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="imageFile" required />
                <img src="@Model.Gorsel" class="img-fluid" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DersId, "DersId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DersId", null, "-- Seçiniz --", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DersId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Durum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Durum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Durum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SinifId, "SinifId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SinifId", null, "-- Seçiniz --", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SinifId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Güncelle" class="btn btn-primary" />
                @Html.ActionLink("Geri Dön", "Index", null, new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
}

LgsKocu.Web/Areas/Admin/Views/AdminSoru/Index.cshtml
@model IEnumerable<LgsKocu.Web.Database.Soru>

@{
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<p>
    @Html.ActionLink("Yeni Soru Ekle", "Create", null, new { @class = "btn btn-primary btn-block" })
</p>
<div class="table-responsive">
    <table class="table table-bordered">
        <tr>
            <th>
                Başlık
            </th>
            <th>
                Üye
            </th>
            <th>
                Durum
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Baslik)
                   
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Uye.Ad) @Html.DisplayFor(modelItem => item.Uye.Soyad)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Durum)
                </td>
                <td>
                    @Html.ActionLink("Güncelle", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("İncele", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Sil", "Delete", new { id = item.Id }) |
                    @Html.ActionLink("Cevaplar", "Index","AdminCevap", new { id = item.Id },null)
                </td>
            </tr>
        }

    </table>
</div>