LgsKocu.Web/Areas/Admin/Controllers/AdminCekilisController.cs
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LgsKocu.Web.Database;

namespace LgsKocu.Web.Areas.Admin.Controllers
{
    public class AdminCekilisController : Controller
    {
        private readonly LgsHazirlikEntities db = new LgsHazirlikEntities();

        public ActionResult Index()
        {
            var cekilis = db.Cekilis.Include(c => c.Ders).Include(c => c.Konu).Include(c => c.Sinif);
            return View(cekilis.ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var cekilis = db.Cekilis.Find(id);
            if (cekilis == null) return HttpNotFound();
            return View(cekilis);
        }

        public ActionResult Create()
        {
            ViewBag.DersId = new SelectList(db.Ders, "Id", "Ad");
            ViewBag.KonuId = new SelectList(db.Konu, "Id", "Ad");
            ViewBag.SinifId = new SelectList(db.Sinif, "Id", "Ad");
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Cekilis cekilis, HttpPostedFileBase imageFile)
        {
            if (ModelState.IsValid)
                if (imageFile != null)
                {
                    if (imageFile.ContentLength > 0)
                    {
                        var path = Path.Combine(Server.MapPath("~/Assets/Files/Cekilis/"), imageFile.FileName);
                        imageFile.SaveAs(path);

                        cekilis.Gorsel = "/Assets/Files/Cekilis/" + imageFile.FileName;

                        db.Cekilis.Add(cekilis);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }


            ViewBag.DersId = new SelectList(db.Ders, "Id", "Ad", cekilis.DersId);
            ViewBag.KonuId = new SelectList(db.Konu, "Id", "Ad", cekilis.KonuId);
            ViewBag.SinifId = new SelectList(db.Sinif, "Id", "Ad", cekilis.SinifId);
            return View(cekilis);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var cekilis = db.Cekilis.Find(id);
            if (cekilis == null) return HttpNotFound();
            ViewBag.DersId = new SelectList(db.Ders, "Id", "Ad", cekilis.DersId);
            ViewBag.KonuId = new SelectList(db.Konu, "Id", "Ad", cekilis.KonuId);
            ViewBag.SinifId = new SelectList(db.Sinif, "Id", "Ad", cekilis.SinifId);
            return View(cekilis);
        }

        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Cekilis cekilis, HttpPostedFileBase imageFile)
        {
            if (ModelState.IsValid)
            {
                if (imageFile != null)
                {
                    if (imageFile.ContentLength > 0)
                    {
                        var path = Path.Combine(Server.MapPath("~/Assets/Files/Cekilis/"), imageFile.FileName);
                        imageFile.SaveAs(path);

                        cekilis.Gorsel = "/Assets/Files/Cekilis/" + imageFile.FileName;
                    }
                }
                else
                {
                    cekilis.Gorsel = db.Cekilis.Find(cekilis.Id).Gorsel;
                }

                db.SaveChanges();
                return RedirectToAction("Index");
            }


            ViewBag.DersId = new SelectList(db.Ders, "Id", "Ad", cekilis.DersId);
            ViewBag.KonuId = new SelectList(db.Konu, "Id", "Ad", cekilis.KonuId);
            ViewBag.SinifId = new SelectList(db.Sinif, "Id", "Ad", cekilis.SinifId);
            return View(cekilis);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var cekilis = db.Cekilis.Find(id);
            if (cekilis == null) return HttpNotFound();
            return View(cekilis);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var cekilis = db.Cekilis.Find(id);
            db.Cekilis.Remove(cekilis);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing) db.Dispose();
            base.Dispose(disposing);
        }
    }
}

LgsKocu.Web/Areas/Admin/Controllers/AdminCekilisKatilimciController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using LgsKocu.Web.Database;

namespace LgsKocu.Web.Areas.Admin.Controllers
{
    public class AdminCekilisKatilimciController : Controller
    {
        private readonly LgsHazirlikEntities db = new LgsHazirlikEntities();

        public ActionResult Index(int? id)
        {
            if (id == null)
            {
                var cekilisKatilimci = db.CekilisKatilimci.Include(c => c.Cekilis).Include(c => c.Uye);
                return View(cekilisKatilimci.ToList());
            }
            else
            {
                var cekilisKatilimci = db.CekilisKatilimci.Where(x => x.CekilisId == id).Include(c => c.Cekilis).Include(c => c.Uye);
                return View(cekilisKatilimci.ToList());
            }
        }

        public ActionResult Details(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var cekilisKatilimci = db.CekilisKatilimci.Find(id);
            if (cekilisKatilimci == null) return HttpNotFound();
            return View(cekilisKatilimci);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var cekilisKatilimci = db.CekilisKatilimci.Find(id);
            if (cekilisKatilimci == null) return HttpNotFound();
            return View(cekilisKatilimci);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var cekilisKatilimci = db.CekilisKatilimci.Find(id);
            db.CekilisKatilimci.Remove(cekilisKatilimci);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing) db.Dispose();
            base.Dispose(disposing);
        }
    }
}

LgsKocu.Web/Areas/Admin/Views/AdminCekilis/Create.cshtml
@model LgsKocu.Web.Database.Cekilis

@{
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("Create","AdminCekilis",FormMethod.Post,new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cekiliş Ekle</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            Ad
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Seo
            <div class="col-md-10">
                @Html.EditorFor(model => model.Seo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Seo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Başlangıç Tarihi
            <div class="col-md-10">
                @Html.EditorFor(model => model.BaslangiTarihi, new { htmlAttributes = new { @class = "form-control datetimepicker" } })
                @Html.ValidationMessageFor(model => model.BaslangiTarihi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Bitiş Tarihi
            <div class="col-md-10">
                @Html.EditorFor(model => model.BitisTarihi, new { htmlAttributes = new { @class = "form-control datetimepicker" } })
                @Html.ValidationMessageFor(model => model.BitisTarihi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Katılımcı Sayısı
            <div class="col-md-10">
                @Html.EditorFor(model => model.KatilimciSayisi, new { @type = "number", @min = "0", @step = "1", @value = "1000", htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KatilimciSayisi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Özet
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ozet, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ozet, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Aciklama, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Aciklama, new { @class = "form-control summernote", @row = 5 })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gorsel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="imageFile" required />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InstagramLink, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InstagramLink, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InstagramLink, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FacebookLink, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FacebookLink, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FacebookLink, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SinifId, "SinifId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SinifId", null, "-- Seçiniz --", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SinifId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DersId, "DersId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DersId", null, "-- Seçiniz --", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DersId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KonuId, "KonuId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("KonuId", null, "-- Seçiniz --", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.KonuId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Durum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Durum)
                    @Html.ValidationMessageFor(model => model.Durum, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Ekle" class="btn btn-primary" />
                @Html.ActionLink("Geri Dön", "Index",null,new{ @class = "btn btn-danger" })
            </div>
        </div>
    </div>
}

LgsKocu.Web/Areas/Admin/Views/AdminCekilis/Delete.cshtml
@model LgsKocu.Web.Database.Cekilis

@{
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div>
    <h4>@Model.Ad >> Sil</h4>
    <hr />
    <hr/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Seo)
        </dt>

        <dd>
            <a href="/@Model.Seo" target="_blank">@Model.Seo</a>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BaslangiTarihi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BaslangiTarihi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BitisTarihi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BitisTarihi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KatilimciSayisi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KatilimciSayisi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ozet)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ozet)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Aciklama)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Aciklama)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gorsel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gorsel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InstagramLink)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InstagramLink)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FacebookLink)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FacebookLink)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Durum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Durum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ders.Ad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ders.Ad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Konu.Ad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Konu.Ad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sinif.Ad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sinif.Ad)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Sil" class="btn btn-primary"/>
            @Html.ActionLink("Geri Dön", "Index", null, new {@class = "btn btn-danger"})
        </div>
    }
</div>

LgsKocu.Web/Areas/Admin/Views/AdminCekilis/Details.cshtml
@model LgsKocu.Web.Database.Cekilis

@{
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div>
    <h4>@Model.Ad >> Detay</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Seo)
        </dt>

        <dd>
            <a href="/@Model.Seo" target="_blank">@Model.Seo</a>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BaslangiTarihi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BaslangiTarihi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BitisTarihi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BitisTarihi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KatilimciSayisi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KatilimciSayisi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ozet)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ozet)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Aciklama)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Aciklama)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gorsel)
        </dt>

        <dd>
            <img src="@Model.Gorsel" class="img-fluid"/>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InstagramLink)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InstagramLink)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FacebookLink)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FacebookLink)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Durum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Durum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ders.Ad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ders.Ad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Konu.Ad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Konu.Ad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sinif.Ad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sinif.Ad)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Güncelle", "Edit", new { id = Model.Id }, new { @class = "btn btn-primary" }) |
    @Html.ActionLink("Sil", "Delete", new { id = Model.Id }, new { @class = "btn btn-warning" }) |
    @Html.ActionLink("Geri Dön", "Index", null, new { @class = "btn btn-danger" })
</p>

LgsKocu.Web/Areas/Admin/Views/AdminCekilis/Edit.cshtml
@model LgsKocu.Web.Database.Cekilis

@{
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("Edit", "AdminCekilis", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>@Model.Ad >> Güncelle</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Ad, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Ad, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Ad, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Seo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Seo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Seo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BaslangiTarihi, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BaslangiTarihi, new { htmlAttributes = new { @class = "form-control datetimepicker" } })
            @Html.ValidationMessageFor(model => model.BaslangiTarihi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BitisTarihi, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BitisTarihi, new { htmlAttributes = new { @class = "form-control datetimepicker" } })
            @Html.ValidationMessageFor(model => model.BitisTarihi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.KatilimciSayisi, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.KatilimciSayisi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.KatilimciSayisi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Ozet, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Ozet, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Ozet, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Aciklama, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Aciklama, new { @class = "form-control summernote", @row = 5 })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Gorsel, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" id="imageFile" name="imageFile" />

            <img src="@Model.Gorsel" class="img-fluid" />
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.InstagramLink, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.InstagramLink, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.InstagramLink, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FacebookLink, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FacebookLink, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FacebookLink, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SinifId, "SinifId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("SinifId", null, "-- Seçiniz --", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.SinifId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DersId, "DersId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("DersId", null, "-- Seçiniz --", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.DersId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.KonuId, "KonuId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("KonuId", null, "-- Seçiniz --", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.KonuId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Durum, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Durum)
                @Html.ValidationMessageFor(model => model.Durum, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Güncelle" class="btn btn-primary" />
            @Html.ActionLink("Geri Dön", "Index", null, new { @class = "btn btn-danger" })
        </div>
    </div>
</div>
}

LgsKocu.Web/Areas/Admin/Views/AdminCekilis/Index.cshtml
@model IEnumerable<LgsKocu.Web.Database.Cekilis>

@{
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<p>
    @Html.ActionLink("Yeni Çekiliş Ekle", "Create", null, new { @class = "btn btn-primary btn-block" })
</p>
<div class="table-responsive">
<table class="table table-bordered">
    <tr>
        <th>
            Ad
        </th>
        <th>
            Seo
        </th>
        <th>
            Başlangıç Tarihi
        </th>
        <th>
            Bitiş Tarihi
        </th>
        <th>
            Katılımcı Sayısı
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Ad)
            </td>
            <td>
                <a href="/@item.Seo" target="_blank">@item.Seo</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BaslangiTarihi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BitisTarihi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CekilisKatilimci.Count)
            </td>
            <td>
                @Html.ActionLink("Güncelle", "Edit", new { id = item.Id }) |
                @Html.ActionLink("İncele", "Details", new { id = item.Id }) |
                @Html.ActionLink("Sil", "Delete", new { id = item.Id }) |
                @Html.ActionLink("Katılımcılar", "Index","AdminCekilisKatilimci", new { id = item.Id },null)
            </td>
        </tr>
    }

</table>
</div>